export default {
	NO_TOKEN: 1,
  TOKEN_DOESNT_MATCH_INSTANCE: 7,
  TOKEN_EXPIRED: 8,
  INVALID_TOKEN: 1010,

  NO_AUTH_SUPPORT: 330,
  NO_AUTH_NAME_OR_CHALLENGE: 331,
  INVALID_NAME_OR_CHALLENGE: 332,
  NO_RULES_FOR_ROLE: 333,
  CANNOT_REFRESH_TOKEN: 334,
  INVALID_RESET_HASH: 801,
  CHALLENGES_DO_NOT_MATCH: 802,
  INVALID_CHALLENGE: 803,

  NO_IDENTITY_PROVIDER_TOKEN: 901,
  IDENTITY_ALREADY_REGISTERED: 902,
  IDENTITY_ID_NOT_FOUND: 903,
  IDENTITY_NOT_FOUND: 904,
  IDENTITY_EMAIL_CONFLICT: 905,
  IDENTITY_MISSING_GROUP: 906, 
}